Pessoa.create!([
  {nome: "Pessoa 2", email: "pessoa2", telefone: "887987312", logradouro: "Rua 2", complemento: "ap2", numero: "2", bairro: "bairro2", municipio_id: 336, cep: "342423423", type: "Candidato", cpf: "4233342322", dataNascimento: "1965-01-01", naturalidade_id: 336, nacionalidade: "Salvador", foto: nil, inscricaoEstadual: nil, cnpj: nil, logo: nil, autorizado: nil},
  {nome: "Contratante 3", email: "pessoa3", telefone: "887987312", logradouro: "Rua 2", complemento: "ap2", numero: "2", bairro: "bairro2", municipio_id: 336, cep: "342423423", type: "Contratante", cpf: "4233342322", dataNascimento: "1965-01-01", naturalidade_id: nil, nacionalidade: nil, foto: nil, inscricaoEstadual: nil, cnpj: nil, logo: nil, autorizado: nil},
  {nome: "Contratante 4", email: "dsad@dfsd", telefone: "2331", logradouro: "34", complemento: "342", numero: "122", bairro: "afça", municipio_id: 8, cep: "34234", type: "Contratante", cpf: nil, dataNascimento: nil, naturalidade_id: nil, nacionalidade: nil, foto: nil, inscricaoEstadual: "3423", cnpj: "3424", logo: "", autorizado: true}
])
FaixaSalarial.create!([
  {valor: "1000"},
  {valor: "2000"},
  {valor: "3000"}
])
GrauFormacao.create!([
  {descricao: "Fundamental"},
  {descricao: "Medio"},
  {descricao: "Superior"},
  {descricao: "Mestrado"},
  {descricao: "Doutorado"}
])
Lingua.create!([
  {descricao: "Ingles"},
  {descricao: "Frances"}
])
Municipio.create!([
  {nome: "Abaré", unidade_federativa_id: 5},
  {nome: "Abaíra", unidade_federativa_id: 5},
  {nome: "Acajutiba", unidade_federativa_id: 5},
  {nome: "Adustina", unidade_federativa_id: 5},
  {nome: "Água Fria", unidade_federativa_id: 5},
  {nome: "Aiquara", unidade_federativa_id: 5},
  {nome: "Alagoinhas", unidade_federativa_id: 5},
  {nome: "Alcobaça", unidade_federativa_id: 5},
  {nome: "Almadina", unidade_federativa_id: 5},
  {nome: "Amargosa", unidade_federativa_id: 5},
  {nome: "Amélia Rodrigues", unidade_federativa_id: 5},
  {nome: "América Dourada", unidade_federativa_id: 5},
  {nome: "Anagé", unidade_federativa_id: 5},
  {nome: "Andaraí", unidade_federativa_id: 5},
  {nome: "Andorinha", unidade_federativa_id: 5},
  {nome: "Angical", unidade_federativa_id: 5},
  {nome: "Anguera", unidade_federativa_id: 5},
  {nome: "Antas", unidade_federativa_id: 5},
  {nome: "Antônio Cardoso", unidade_federativa_id: 5},
  {nome: "Antônio Gonçalves", unidade_federativa_id: 5},
  {nome: "Aporá", unidade_federativa_id: 5},
  {nome: "Apuarema", unidade_federativa_id: 5},
  {nome: "Aracatu", unidade_federativa_id: 5},
  {nome: "Araci", unidade_federativa_id: 5},
  {nome: "Aramari", unidade_federativa_id: 5},
  {nome: "Arataca", unidade_federativa_id: 5},
  {nome: "Aratuípe", unidade_federativa_id: 5},
  {nome: "Araças", unidade_federativa_id: 5},
  {nome: "Aurelino Leal", unidade_federativa_id: 5},
  {nome: "Baianópolis", unidade_federativa_id: 5},
  {nome: "Baixa Grande", unidade_federativa_id: 5},
  {nome: "Banzaê", unidade_federativa_id: 5},
  {nome: "Barra", unidade_federativa_id: 5},
  {nome: "Barra da Estiva", unidade_federativa_id: 5},
  {nome: "Barra do Choça", unidade_federativa_id: 5},
  {nome: "Barra do Mes", unidade_federativa_id: 5},
  {nome: "Barra do Rocha", unidade_federativa_id: 5},
  {nome: "Barreiras", unidade_federativa_id: 5},
  {nome: "Barro Alto", unidade_federativa_id: 5},
  {nome: "Barro Preto", unidade_federativa_id: 5},
  {nome: "Barrocas", unidade_federativa_id: 5},
  {nome: "Belmonte", unidade_federativa_id: 5},
  {nome: "Belo Campo", unidade_federativa_id: 5},
  {nome: "Biritinga", unidade_federativa_id: 5},
  {nome: "Boa Nova", unidade_federativa_id: 5},
  {nome: "Boa Vista do Tupim", unidade_federativa_id: 5},
  {nome: "Bom Jesus da Lapa", unidade_federativa_id: 5},
  {nome: "Bom Jesus da Serra", unidade_federativa_id: 5},
  {nome: "Boninal", unidade_federativa_id: 5},
  {nome: "Bonito", unidade_federativa_id: 5},
  {nome: "Boquira", unidade_federativa_id: 5},
  {nome: "Botuporã", unidade_federativa_id: 5},
  {nome: "Brejolândia", unidade_federativa_id: 5},
  {nome: "Brejões", unidade_federativa_id: 5},
  {nome: "Brotas de Macaúbas", unidade_federativa_id: 5},
  {nome: "Brumado", unidade_federativa_id: 5},
  {nome: "Buerarema", unidade_federativa_id: 5},
  {nome: "Buritirama", unidade_federativa_id: 5},
  {nome: "Caatiba", unidade_federativa_id: 5},
  {nome: "Cabaceiras do Paraguaçu", unidade_federativa_id: 5},
  {nome: "Cachoeira", unidade_federativa_id: 5},
  {nome: "Caculé", unidade_federativa_id: 5},
  {nome: "Caetanos", unidade_federativa_id: 5},
  {nome: "Caetité", unidade_federativa_id: 5},
  {nome: "Cafarnaum", unidade_federativa_id: 5},
  {nome: "Cairu", unidade_federativa_id: 5},
  {nome: "Caldeirão Grande", unidade_federativa_id: 5},
  {nome: "Camacan", unidade_federativa_id: 5},
  {nome: "Camamu", unidade_federativa_id: 5},
  {nome: "Camaçari", unidade_federativa_id: 5},
  {nome: "Campo Alegre de Lourdes", unidade_federativa_id: 5},
  {nome: "Campo Formoso", unidade_federativa_id: 5},
  {nome: "Canarana", unidade_federativa_id: 5},
  {nome: "Canavieiras", unidade_federativa_id: 5},
  {nome: "Candeal", unidade_federativa_id: 5},
  {nome: "Candeias", unidade_federativa_id: 5},
  {nome: "Candiba", unidade_federativa_id: 5},
  {nome: "Cansanção", unidade_federativa_id: 5},
  {nome: "Canudos", unidade_federativa_id: 5},
  {nome: "Canápolis", unidade_federativa_id: 5},
  {nome: "Capela do Alto Alegre", unidade_federativa_id: 5},
  {nome: "Capim Grosso", unidade_federativa_id: 5},
  {nome: "Caravelas", unidade_federativa_id: 5},
  {nome: "Caraíbas", unidade_federativa_id: 5},
  {nome: "Cardeal da Silva", unidade_federativa_id: 5},
  {nome: "Carinhanha", unidade_federativa_id: 5},
  {nome: "Casa Nova", unidade_federativa_id: 5},
  {nome: "Castro Alves", unidade_federativa_id: 5},
  {nome: "Catolândia", unidade_federativa_id: 5},
  {nome: "Catu", unidade_federativa_id: 5},
  {nome: "Caturama", unidade_federativa_id: 5},
  {nome: "Caém", unidade_federativa_id: 5},
  {nome: "Central", unidade_federativa_id: 5},
  {nome: "Chorrochó", unidade_federativa_id: 5},
  {nome: "Cipó", unidade_federativa_id: 5},
  {nome: "Coaraci", unidade_federativa_id: 5},
  {nome: "Cocos", unidade_federativa_id: 5},
  {nome: "Conceição da Feira", unidade_federativa_id: 5},
  {nome: "Conceição do Almeida", unidade_federativa_id: 5},
  {nome: "Conceição do Coité", unidade_federativa_id: 5},
  {nome: "Conceição do Jacuípe", unidade_federativa_id: 5},
  {nome: "Conde", unidade_federativa_id: 5},
  {nome: "Condeúba", unidade_federativa_id: 5},
  {nome: "Contas do Sincorá", unidade_federativa_id: 5},
  {nome: "Coração de Maria", unidade_federativa_id: 5},
  {nome: "Cordeiros", unidade_federativa_id: 5},
  {nome: "Coribe", unidade_federativa_id: 5},
  {nome: "Coronel João Sá", unidade_federativa_id: 5},
  {nome: "Correntina", unidade_federativa_id: 5},
  {nome: "Cotegipe", unidade_federativa_id: 5},
  {nome: "Cravolândia", unidade_federativa_id: 5},
  {nome: "Cristópolis", unidade_federativa_id: 5},
  {nome: "Crisópolis", unidade_federativa_id: 5},
  {nome: "Cruz das Almas", unidade_federativa_id: 5},
  {nome: "Curaçá", unidade_federativa_id: 5},
  {nome: "Cândido Sales", unidade_federativa_id: 5},
  {nome: "Cícero Dantas", unidade_federativa_id: 5},
  {nome: "Dias d'Ávila", unidade_federativa_id: 5},
  {nome: "Dom Basílio", unidade_federativa_id: 5},
  {nome: "Dom Macedo Costa", unidade_federativa_id: 5},
  {nome: "Dário Meira", unidade_federativa_id: 5},
  {nome: "Elísio Medrado", unidade_federativa_id: 5},
  {nome: "Encruzilhada", unidade_federativa_id: 5},
  {nome: "Entre Rios", unidade_federativa_id: 5},
  {nome: "Érico Cardoso", unidade_federativa_id: 5},
  {nome: "Esplanada", unidade_federativa_id: 5},
  {nome: "Euclides da Cunha", unidade_federativa_id: 5},
  {nome: "Eunápolis", unidade_federativa_id: 5},
  {nome: "Feira da Mata", unidade_federativa_id: 5},
  {nome: "Feira de Santana", unidade_federativa_id: 5},
  {nome: "Filadélfia", unidade_federativa_id: 5},
  {nome: "Firmino Alves", unidade_federativa_id: 5},
  {nome: "Floresta Azul", unidade_federativa_id: 5},
  {nome: "Formosa do Rio Preto", unidade_federativa_id: 5},
  {nome: "Fátima", unidade_federativa_id: 5},
  {nome: "Gandu", unidade_federativa_id: 5},
  {nome: "Gavião", unidade_federativa_id: 5},
  {nome: "Gentio do Ouro", unidade_federativa_id: 5},
  {nome: "Glória", unidade_federativa_id: 5},
  {nome: "Gongogi", unidade_federativa_id: 5},
  {nome: "Governador Mangabeira", unidade_federativa_id: 5},
  {nome: "Guajeru", unidade_federativa_id: 5},
  {nome: "Guanambi", unidade_federativa_id: 5},
  {nome: "Guaratinga", unidade_federativa_id: 5},
  {nome: "Heliópolis", unidade_federativa_id: 5},
  {nome: "Iaçu", unidade_federativa_id: 5},
  {nome: "Ibiassucê", unidade_federativa_id: 5},
  {nome: "Ibicaraí", unidade_federativa_id: 5},
  {nome: "Ibicoara", unidade_federativa_id: 5},
  {nome: "Ibicuí", unidade_federativa_id: 5},
  {nome: "Ibipeba", unidade_federativa_id: 5},
  {nome: "Ibipitanga", unidade_federativa_id: 5},
  {nome: "Ibiquera", unidade_federativa_id: 5},
  {nome: "Ibirapitanga", unidade_federativa_id: 5},
  {nome: "Ibirapuã", unidade_federativa_id: 5},
  {nome: "Ibirataia", unidade_federativa_id: 5},
  {nome: "Ibitiara", unidade_federativa_id: 5},
  {nome: "Ibititá", unidade_federativa_id: 5},
  {nome: "Ibotirama", unidade_federativa_id: 5},
  {nome: "Ichu", unidade_federativa_id: 5},
  {nome: "Igaporã", unidade_federativa_id: 5},
  {nome: "Igrapiúna", unidade_federativa_id: 5},
  {nome: "Iguaí", unidade_federativa_id: 5},
  {nome: "Ilhéus", unidade_federativa_id: 5},
  {nome: "Inhambupe", unidade_federativa_id: 5},
  {nome: "Ipecaetá", unidade_federativa_id: 5},
  {nome: "Ipiaú", unidade_federativa_id: 5},
  {nome: "Ipirá", unidade_federativa_id: 5},
  {nome: "Ipupiara", unidade_federativa_id: 5},
  {nome: "Irajuba", unidade_federativa_id: 5},
  {nome: "Iramaia", unidade_federativa_id: 5},
  {nome: "Iraquara", unidade_federativa_id: 5},
  {nome: "Irará", unidade_federativa_id: 5},
  {nome: "Irecê", unidade_federativa_id: 5},
  {nome: "Itabela", unidade_federativa_id: 5},
  {nome: "Itaberaba", unidade_federativa_id: 5},
  {nome: "Itabuna", unidade_federativa_id: 5},
  {nome: "Itacaré", unidade_federativa_id: 5},
  {nome: "Itaeté", unidade_federativa_id: 5},
  {nome: "Itagi", unidade_federativa_id: 5},
  {nome: "Itagibá", unidade_federativa_id: 5},
  {nome: "Itagimirim", unidade_federativa_id: 5},
  {nome: "Itaguaçu da Bahia", unidade_federativa_id: 5},
  {nome: "Itaju do Colônia", unidade_federativa_id: 5},
  {nome: "Itajuípe", unidade_federativa_id: 5},
  {nome: "Itamaraju", unidade_federativa_id: 5},
  {nome: "Itamari", unidade_federativa_id: 5},
  {nome: "Itambé", unidade_federativa_id: 5},
  {nome: "Itanagra", unidade_federativa_id: 5},
  {nome: "Itanhém", unidade_federativa_id: 5},
  {nome: "Itaparica", unidade_federativa_id: 5},
  {nome: "Itapebi", unidade_federativa_id: 5},
  {nome: "Itapetinga", unidade_federativa_id: 5},
  {nome: "Itapicuru", unidade_federativa_id: 5},
  {nome: "Itapitanga", unidade_federativa_id: 5},
  {nome: "Itapé", unidade_federativa_id: 5},
  {nome: "Itaquara", unidade_federativa_id: 5},
  {nome: "Itarantim", unidade_federativa_id: 5},
  {nome: "Itatim", unidade_federativa_id: 5},
  {nome: "Itiruçu", unidade_federativa_id: 5},
  {nome: "Itiúba", unidade_federativa_id: 5},
  {nome: "Itororó", unidade_federativa_id: 5},
  {nome: "Ituaçu", unidade_federativa_id: 5},
  {nome: "Ituberá", unidade_federativa_id: 5},
  {nome: "Iuiú", unidade_federativa_id: 5},
  {nome: "Jaborandi", unidade_federativa_id: 5},
  {nome: "Jacaraci", unidade_federativa_id: 5},
  {nome: "Jacobina", unidade_federativa_id: 5},
  {nome: "Jaguaquara", unidade_federativa_id: 5},
  {nome: "Jaguarari", unidade_federativa_id: 5},
  {nome: "Jaguaripe", unidade_federativa_id: 5},
  {nome: "Jandaíra", unidade_federativa_id: 5},
  {nome: "Jequié", unidade_federativa_id: 5},
  {nome: "Jeremoabo", unidade_federativa_id: 5},
  {nome: "Jiquiriçá", unidade_federativa_id: 5},
  {nome: "Jitaúna", unidade_federativa_id: 5},
  {nome: "João Dourado", unidade_federativa_id: 5},
  {nome: "Juazeiro", unidade_federativa_id: 5},
  {nome: "Jucuruçu", unidade_federativa_id: 5},
  {nome: "Jussara", unidade_federativa_id: 5},
  {nome: "Jussari", unidade_federativa_id: 5},
  {nome: "Jussiape", unidade_federativa_id: 5},
  {nome: "Lafaiete Coutinho", unidade_federativa_id: 5},
  {nome: "Lagoa Real", unidade_federativa_id: 5},
  {nome: "Laje", unidade_federativa_id: 5},
  {nome: "Lajedinho", unidade_federativa_id: 5},
  {nome: "Lajedo do Tabocal", unidade_federativa_id: 5},
  {nome: "Lajedão", unidade_federativa_id: 5},
  {nome: "Lamarão", unidade_federativa_id: 5},
  {nome: "Lapão", unidade_federativa_id: 5},
  {nome: "Lauro de Freitas", unidade_federativa_id: 5},
  {nome: "Lençóis", unidade_federativa_id: 5},
  {nome: "Licínio de Almeida", unidade_federativa_id: 5},
  {nome: "Livramento de Nossa Senhora", unidade_federativa_id: 5},
  {nome: "Luís Eduardo Magalhães", unidade_federativa_id: 5},
  {nome: "Macajuba", unidade_federativa_id: 5},
  {nome: "Macarani", unidade_federativa_id: 5},
  {nome: "Macaúbas", unidade_federativa_id: 5},
  {nome: "Macururé", unidade_federativa_id: 5},
  {nome: "Madre de Deus", unidade_federativa_id: 5},
  {nome: "Maetinga", unidade_federativa_id: 5},
  {nome: "Maiquinique", unidade_federativa_id: 5},
  {nome: "Mairi", unidade_federativa_id: 5},
  {nome: "Malhada", unidade_federativa_id: 5},
  {nome: "Malhada de Pedras", unidade_federativa_id: 5},
  {nome: "Manoel Vitorino", unidade_federativa_id: 5},
  {nome: "Mansidão", unidade_federativa_id: 5},
  {nome: "Maracás", unidade_federativa_id: 5},
  {nome: "Maragogipe", unidade_federativa_id: 5},
  {nome: "Maraú", unidade_federativa_id: 5},
  {nome: "Marcionílio Souza", unidade_federativa_id: 5},
  {nome: "Mascote", unidade_federativa_id: 5},
  {nome: "Mata de São João", unidade_federativa_id: 5},
  {nome: "Matina", unidade_federativa_id: 5},
  {nome: "Medeiros Neto", unidade_federativa_id: 5},
  {nome: "Miguel Calmon", unidade_federativa_id: 5},
  {nome: "Milagres", unidade_federativa_id: 5},
  {nome: "Mirangaba", unidade_federativa_id: 5},
  {nome: "Mirante", unidade_federativa_id: 5},
  {nome: "Monte Santo", unidade_federativa_id: 5},
  {nome: "Morpará", unidade_federativa_id: 5},
  {nome: "Morro do Chapéu", unidade_federativa_id: 5},
  {nome: "Mortugaba", unidade_federativa_id: 5},
  {nome: "Mucugê", unidade_federativa_id: 5},
  {nome: "Mucuri", unidade_federativa_id: 5},
  {nome: "Mulungu do Morro", unidade_federativa_id: 5},
  {nome: "Mundo Novo", unidade_federativa_id: 5},
  {nome: "Muniz Ferreira", unidade_federativa_id: 5},
  {nome: "Muquém de São Francisco", unidade_federativa_id: 5},
  {nome: "Muritiba", unidade_federativa_id: 5},
  {nome: "Mutuípe", unidade_federativa_id: 5},
  {nome: "Nazaré", unidade_federativa_id: 5},
  {nome: "Nilo Peçanha", unidade_federativa_id: 5},
  {nome: "Nordestina", unidade_federativa_id: 5},
  {nome: "Nova Canaã", unidade_federativa_id: 5},
  {nome: "Nova Fátima", unidade_federativa_id: 5},
  {nome: "Nova Ibiá", unidade_federativa_id: 5},
  {nome: "Nova Itarana", unidade_federativa_id: 5},
  {nome: "Nova Redenção", unidade_federativa_id: 5},
  {nome: "Nova Soure", unidade_federativa_id: 5},
  {nome: "Nova Viçosa", unidade_federativa_id: 5},
  {nome: "Novo Horizonte", unidade_federativa_id: 5},
  {nome: "Novo Triunfo", unidade_federativa_id: 5},
  {nome: "Olindina", unidade_federativa_id: 5},
  {nome: "Oliveira dos Brejinhos", unidade_federativa_id: 5},
  {nome: "Ouriçangas", unidade_federativa_id: 5},
  {nome: "Ourolândia", unidade_federativa_id: 5},
  {nome: "Palmas de Monte Alto", unidade_federativa_id: 5},
  {nome: "Palmeiras", unidade_federativa_id: 5},
  {nome: "Paramirim", unidade_federativa_id: 5},
  {nome: "Paratinga", unidade_federativa_id: 5},
  {nome: "Paripiranga", unidade_federativa_id: 5},
  {nome: "Pau Brasil", unidade_federativa_id: 5},
  {nome: "Paulo Afonso", unidade_federativa_id: 5},
  {nome: "Pedro Alexandre", unidade_federativa_id: 5},
  {nome: "Pedrão", unidade_federativa_id: 5},
  {nome: "Piatã", unidade_federativa_id: 5},
  {nome: "Pilão Arcado", unidade_federativa_id: 5},
  {nome: "Pindaí", unidade_federativa_id: 5},
  {nome: "Pindobaçu", unidade_federativa_id: 5},
  {nome: "Pintadas", unidade_federativa_id: 5},
  {nome: "Piraí do Norte", unidade_federativa_id: 5},
  {nome: "Piripá", unidade_federativa_id: 5},
  {nome: "Piritiba", unidade_federativa_id: 5},
  {nome: "Planaltino", unidade_federativa_id: 5},
  {nome: "Planalto", unidade_federativa_id: 5},
  {nome: "Pojuca", unidade_federativa_id: 5},
  {nome: "Ponto Novo", unidade_federativa_id: 5},
  {nome: "Porto Seguro", unidade_federativa_id: 5},
  {nome: "Potiraguá", unidade_federativa_id: 5},
  {nome: "Poções", unidade_federativa_id: 5},
  {nome: "Prado", unidade_federativa_id: 5},
  {nome: "Presidente Dutra", unidade_federativa_id: 5},
  {nome: "Presidente Jânio Quadros", unidade_federativa_id: 5},
  {nome: "Presidente Tancredo Neves", unidade_federativa_id: 5},
  {nome: "Pé de Serra", unidade_federativa_id: 5},
  {nome: "Queimadas", unidade_federativa_id: 5},
  {nome: "Quijingue", unidade_federativa_id: 5},
  {nome: "Quixabeira", unidade_federativa_id: 5},
  {nome: "Rafael Jambeiro", unidade_federativa_id: 5},
  {nome: "Remanso", unidade_federativa_id: 5},
  {nome: "Retirolândia", unidade_federativa_id: 5},
  {nome: "Riacho de Santana", unidade_federativa_id: 5},
  {nome: "Riachão das Neves", unidade_federativa_id: 5},
  {nome: "Riachão do Jacuípe", unidade_federativa_id: 5},
  {nome: "Ribeira do Amparo", unidade_federativa_id: 5},
  {nome: "Ribeira do Pombal", unidade_federativa_id: 5},
  {nome: "Ribeirão do Largo", unidade_federativa_id: 5},
  {nome: "Rio Real", unidade_federativa_id: 5},
  {nome: "Rio de Contas", unidade_federativa_id: 5},
  {nome: "Rio do Antônio", unidade_federativa_id: 5},
  {nome: "Rio do Pires", unidade_federativa_id: 5},
  {nome: "Rodelas", unidade_federativa_id: 5},
  {nome: "Ruy Barbosa", unidade_federativa_id: 5},
  {nome: "Salinas da Margarida", unidade_federativa_id: 5},
  {nome: "Salvador", unidade_federativa_id: 5},
  {nome: "Santa Brígida", unidade_federativa_id: 5},
  {nome: "Santa Bárbara", unidade_federativa_id: 5},
  {nome: "Santa Cruz Cabrália", unidade_federativa_id: 5},
  {nome: "Santa Cruz da Vitória", unidade_federativa_id: 5},
  {nome: "Santa Inês", unidade_federativa_id: 5},
  {nome: "Santa Luzia", unidade_federativa_id: 5},
  {nome: "Santa Maria da Vitória", unidade_federativa_id: 5},
  {nome: "Santa Rita de Cássia", unidade_federativa_id: 5},
  {nome: "Santa Teresinha", unidade_federativa_id: 5},
  {nome: "Santaluz", unidade_federativa_id: 5},
  {nome: "Santana", unidade_federativa_id: 5},
  {nome: "Santanópolis", unidade_federativa_id: 5},
  {nome: "Santo Amaro", unidade_federativa_id: 5},
  {nome: "Santo Antônio de Jesus", unidade_federativa_id: 5},
  {nome: "Santo Estêvão", unidade_federativa_id: 5},
  {nome: "Sapeaçu", unidade_federativa_id: 5},
  {nome: "Saubara", unidade_federativa_id: 5},
  {nome: "Saúde", unidade_federativa_id: 5},
  {nome: "Seabra", unidade_federativa_id: 5},
  {nome: "Sebastião Laranjeiras", unidade_federativa_id: 5},
  {nome: "Senhor do Bonfim", unidade_federativa_id: 5},
  {nome: "Sento Sé", unidade_federativa_id: 5},
  {nome: "Serra Dourada", unidade_federativa_id: 5},
  {nome: "Serra Preta", unidade_federativa_id: 5},
  {nome: "Serra do Ramalho", unidade_federativa_id: 5},
  {nome: "Serrinha", unidade_federativa_id: 5},
  {nome: "Serrolândia", unidade_federativa_id: 5},
  {nome: "Simões Filho", unidade_federativa_id: 5},
  {nome: "Sobradinho", unidade_federativa_id: 5},
  {nome: "Souto Soares", unidade_federativa_id: 5},
  {nome: "Sátiro Dias", unidade_federativa_id: 5},
  {nome: "São Desidério", unidade_federativa_id: 5},
  {nome: "São Domingos", unidade_federativa_id: 5},
  {nome: "São Felipe", unidade_federativa_id: 5},
  {nome: "São Francisco do Conde", unidade_federativa_id: 5},
  {nome: "São Félix", unidade_federativa_id: 5},
  {nome: "São Félix do Coribe", unidade_federativa_id: 5},
  {nome: "São Gabriel", unidade_federativa_id: 5},
  {nome: "São Gonçalo dos Campos", unidade_federativa_id: 5},
  {nome: "São José da Vitória", unidade_federativa_id: 5},
  {nome: "São José do Jacuípe", unidade_federativa_id: 5},
  {nome: "São Miguel das Matas", unidade_federativa_id: 5},
  {nome: "São Sebastião do Passé", unidade_federativa_id: 5},
  {nome: "Sítio do Mato", unidade_federativa_id: 5},
  {nome: "Sítio do Quinto", unidade_federativa_id: 5},
  {nome: "Tabocas do Brejo Velho", unidade_federativa_id: 5},
  {nome: "Tanhaçu", unidade_federativa_id: 5},
  {nome: "Tanque Novo", unidade_federativa_id: 5},
  {nome: "Tanquinho", unidade_federativa_id: 5},
  {nome: "Taperoá", unidade_federativa_id: 5},
  {nome: "Tapiramutá", unidade_federativa_id: 5},
  {nome: "Teixeira de Freitas", unidade_federativa_id: 5},
  {nome: "Teodoro Sampaio", unidade_federativa_id: 5},
  {nome: "Teofilândia", unidade_federativa_id: 5},
  {nome: "Teolândia", unidade_federativa_id: 5},
  {nome: "Terra Nova", unidade_federativa_id: 5},
  {nome: "Tremedal", unidade_federativa_id: 5},
  {nome: "Tucano", unidade_federativa_id: 5},
  {nome: "Uauá", unidade_federativa_id: 5},
  {nome: "Ubaitaba", unidade_federativa_id: 5},
  {nome: "Ubatã", unidade_federativa_id: 5},
  {nome: "Ubaíra", unidade_federativa_id: 5},
  {nome: "Uibaí", unidade_federativa_id: 5},
  {nome: "Umburanas", unidade_federativa_id: 5},
  {nome: "Una", unidade_federativa_id: 5},
  {nome: "Urandi", unidade_federativa_id: 5},
  {nome: "Uruçuca", unidade_federativa_id: 5},
  {nome: "Utinga", unidade_federativa_id: 5},
  {nome: "Valente", unidade_federativa_id: 5},
  {nome: "Valença", unidade_federativa_id: 5},
  {nome: "Varzedo", unidade_federativa_id: 5},
  {nome: "Vera Cruz", unidade_federativa_id: 5},
  {nome: "Vereda", unidade_federativa_id: 5},
  {nome: "Vitória da Conquista", unidade_federativa_id: 5},
  {nome: "Várzea Nova", unidade_federativa_id: 5},
  {nome: "Várzea da Roça", unidade_federativa_id: 5},
  {nome: "Várzea do Poço", unidade_federativa_id: 5},
  {nome: "Wagner", unidade_federativa_id: 5},
  {nome: "Wanderley", unidade_federativa_id: 5},
  {nome: "Wenceslau Guimarães", unidade_federativa_id: 5},
  {nome: "Xique-Xique", unidade_federativa_id: 5},
  {nome: "Abreulândia", unidade_federativa_id: 27},
  {nome: "Aguiarnópolis", unidade_federativa_id: 27},
  {nome: "Aliança do Tocantins", unidade_federativa_id: 27},
  {nome: "Almas", unidade_federativa_id: 27},
  {nome: "Alvorada", unidade_federativa_id: 27},
  {nome: "Ananás", unidade_federativa_id: 27},
  {nome: "Angico", unidade_federativa_id: 27},
  {nome: "Aparecida do Rio Negro", unidade_federativa_id: 27},
  {nome: "Aragominas", unidade_federativa_id: 27},
  {nome: "Araguacema", unidade_federativa_id: 27},
  {nome: "Araguanã", unidade_federativa_id: 27},
  {nome: "Araguatins", unidade_federativa_id: 27},
  {nome: "Araguaçu", unidade_federativa_id: 27},
  {nome: "Araguaína", unidade_federativa_id: 27},
  {nome: "Arapoema", unidade_federativa_id: 27},
  {nome: "Arraias", unidade_federativa_id: 27},
  {nome: "Augustinópolis", unidade_federativa_id: 27},
  {nome: "Aurora do Tocantins", unidade_federativa_id: 27},
  {nome: "Axixá do Tocantins", unidade_federativa_id: 27},
  {nome: "Babaçulândia", unidade_federativa_id: 27},
  {nome: "Bandeirantes do Tocantins", unidade_federativa_id: 27},
  {nome: "Barra do Ouro", unidade_federativa_id: 27},
  {nome: "Barrolândia", unidade_federativa_id: 27},
  {nome: "Bernardo Sayão", unidade_federativa_id: 27},
  {nome: "Bom Jesus do Tocantins", unidade_federativa_id: 27},
  {nome: "Brasilândia do Tocantins", unidade_federativa_id: 27},
  {nome: "Brejinho de Nazaré", unidade_federativa_id: 27},
  {nome: "Buriti do Tocantins", unidade_federativa_id: 27},
  {nome: "Cachoeirinha", unidade_federativa_id: 27},
  {nome: "Campos Lindos", unidade_federativa_id: 27},
  {nome: "Cariri do Tocantins", unidade_federativa_id: 27},
  {nome: "Carmolândia", unidade_federativa_id: 27},
  {nome: "Carrasco Bonito", unidade_federativa_id: 27},
  {nome: "Caseara", unidade_federativa_id: 27},
  {nome: "Centenário", unidade_federativa_id: 27},
  {nome: "Chapada da Natividade", unidade_federativa_id: 27},
  {nome: "Chapada de Areia", unidade_federativa_id: 27},
  {nome: "Colinas do Tocantins", unidade_federativa_id: 27},
  {nome: "Colméia", unidade_federativa_id: 27},
  {nome: "Combinado", unidade_federativa_id: 27},
  {nome: "Conceição do Tocantins", unidade_federativa_id: 27},
  {nome: "Couto de Magalhães", unidade_federativa_id: 27},
  {nome: "Cristalândia", unidade_federativa_id: 27},
  {nome: "Crixás do Tocantins", unidade_federativa_id: 27},
  {nome: "Darcinópolis", unidade_federativa_id: 27},
  {nome: "Dianópolis", unidade_federativa_id: 27},
  {nome: "Divinópolis do Tocantins", unidade_federativa_id: 27},
  {nome: "Dois Irmãos do Tocantins", unidade_federativa_id: 27},
  {nome: "Dueré", unidade_federativa_id: 27},
  {nome: "Esperantina", unidade_federativa_id: 27},
  {nome: "Figueirópolis", unidade_federativa_id: 27},
  {nome: "Filadélfia", unidade_federativa_id: 27},
  {nome: "Formoso do Araguaia", unidade_federativa_id: 27},
  {nome: "Fortaleza do Tabocão", unidade_federativa_id: 27},
  {nome: "Fátima", unidade_federativa_id: 27},
  {nome: "Goianorte", unidade_federativa_id: 27},
  {nome: "Goiatins", unidade_federativa_id: 27},
  {nome: "Guaraí", unidade_federativa_id: 27},
  {nome: "Gurupi", unidade_federativa_id: 27},
  {nome: "Ipueiras", unidade_federativa_id: 27},
  {nome: "Itacajá", unidade_federativa_id: 27},
  {nome: "Itaguatins", unidade_federativa_id: 27},
  {nome: "Itapiratins", unidade_federativa_id: 27},
  {nome: "Itaporã do Tocantins", unidade_federativa_id: 27},
  {nome: "Jaú do Tocantins", unidade_federativa_id: 27},
  {nome: "Juarina", unidade_federativa_id: 27},
  {nome: "Lagoa da Confusão", unidade_federativa_id: 27},
  {nome: "Lagoa do Tocantins", unidade_federativa_id: 27},
  {nome: "Lajeado", unidade_federativa_id: 27},
  {nome: "Lavandeira", unidade_federativa_id: 27},
  {nome: "Lizarda", unidade_federativa_id: 27},
  {nome: "Luzinópolis", unidade_federativa_id: 27},
  {nome: "Marianópolis do Tocantins", unidade_federativa_id: 27},
  {nome: "Mateiros", unidade_federativa_id: 27},
  {nome: "Maurilândia do Tocantins", unidade_federativa_id: 27},
  {nome: "Miracema do Tocantins", unidade_federativa_id: 27},
  {nome: "Miranorte", unidade_federativa_id: 27},
  {nome: "Monte Santo do Tocantins", unidade_federativa_id: 27},
  {nome: "Monte do Carmo", unidade_federativa_id: 27},
  {nome: "Muricilândia", unidade_federativa_id: 27},
  {nome: "Natividade", unidade_federativa_id: 27},
  {nome: "Nazaré", unidade_federativa_id: 27},
  {nome: "Nova Olinda", unidade_federativa_id: 27},
  {nome: "Nova Rosalândia", unidade_federativa_id: 27},
  {nome: "Novo Acordo", unidade_federativa_id: 27},
  {nome: "Novo Alegre", unidade_federativa_id: 27},
  {nome: "Novo Jardim", unidade_federativa_id: 27},
  {nome: "Oliveira de Fátima", unidade_federativa_id: 27},
  {nome: "Palmas", unidade_federativa_id: 27},
  {nome: "Palmeirante", unidade_federativa_id: 27},
  {nome: "Palmeiras do Tocantins", unidade_federativa_id: 27},
  {nome: "Palmeirópolis", unidade_federativa_id: 27},
  {nome: "Paranã", unidade_federativa_id: 27},
  {nome: "Paraíso do Tocantins", unidade_federativa_id: 27},
  {nome: "Pau D'Arco", unidade_federativa_id: 27},
  {nome: "Pedro Afonso", unidade_federativa_id: 27},
  {nome: "Peixe", unidade_federativa_id: 27},
  {nome: "Pequizeiro", unidade_federativa_id: 27},
  {nome: "Pindorama do Tocantins", unidade_federativa_id: 27},
  {nome: "Piraquê", unidade_federativa_id: 27},
  {nome: "Pium", unidade_federativa_id: 27},
  {nome: "Ponte Alta do Bom Jesus", unidade_federativa_id: 27},
  {nome: "Ponte Alta do Tocantins", unidade_federativa_id: 27},
  {nome: "Porto Alegre do Tocantins", unidade_federativa_id: 27},
  {nome: "Porto Nacional", unidade_federativa_id: 27},
  {nome: "Praia Norte", unidade_federativa_id: 27},
  {nome: "Presidente Kennedy", unidade_federativa_id: 27},
  {nome: "Pugmil", unidade_federativa_id: 27},
  {nome: "Recursolândia", unidade_federativa_id: 27},
  {nome: "Riachinho", unidade_federativa_id: 27},
  {nome: "Rio Sono", unidade_federativa_id: 27},
  {nome: "Rio da Conceição", unidade_federativa_id: 27},
  {nome: "Rio dos Bois", unidade_federativa_id: 27},
  {nome: "Sampaio", unidade_federativa_id: 27},
  {nome: "Sandolândia", unidade_federativa_id: 27},
  {nome: "Santa Fé do Araguaia", unidade_federativa_id: 27},
  {nome: "Santa Maria do Tocantins", unidade_federativa_id: 27},
  {nome: "Santa Rita do Tocantins", unidade_federativa_id: 27},
  {nome: "Santa Rosa do Tocantins", unidade_federativa_id: 27},
  {nome: "Santa Tereza do Tocantins", unidade_federativa_id: 27},
  {nome: "Santa Terezinha do Tocantins", unidade_federativa_id: 27},
  {nome: "Silvanópolis", unidade_federativa_id: 27},
  {nome: "Sucupira", unidade_federativa_id: 27},
  {nome: "São Bento do Tocantins", unidade_federativa_id: 27},
  {nome: "São Félix do Tocantins", unidade_federativa_id: 27},
  {nome: "São Miguel do Tocantins", unidade_federativa_id: 27},
  {nome: "São Salvador do Tocantins", unidade_federativa_id: 27},
  {nome: "São Sebastião do Tocantins", unidade_federativa_id: 27},
  {nome: "São Valério da Natividade", unidade_federativa_id: 27},
  {nome: "Sítio Novo do Tocantins", unidade_federativa_id: 27},
  {nome: "Taguatinga", unidade_federativa_id: 27},
  {nome: "Taipas do Tocantins", unidade_federativa_id: 27},
  {nome: "Talismã", unidade_federativa_id: 27},
  {nome: "Tocantinópolis", unidade_federativa_id: 27},
  {nome: "Tocantínia", unidade_federativa_id: 27},
  {nome: "Tupirama", unidade_federativa_id: 27},
  {nome: "Tupiratins", unidade_federativa_id: 27},
  {nome: "Wanderlândia", unidade_federativa_id: 27},
  {nome: "Xambioá", unidade_federativa_id: 27},
  {nome: "Acauã", unidade_federativa_id: 28},
  {nome: "Agricolândia", unidade_federativa_id: 28},
  {nome: "Água Branca", unidade_federativa_id: 28},
  {nome: "Alagoinha do Piauí", unidade_federativa_id: 28},
  {nome: "Alegrete do Piauí", unidade_federativa_id: 28},
  {nome: "Alto Longá", unidade_federativa_id: 28},
  {nome: "Altos", unidade_federativa_id: 28},
  {nome: "Alvorada do Gurguéia", unidade_federativa_id: 28},
  {nome: "Amarante", unidade_federativa_id: 28},
  {nome: "Angical do Piauí", unidade_federativa_id: 28},
  {nome: "Antônio Almeida", unidade_federativa_id: 28},
  {nome: "Anísio de Abreu", unidade_federativa_id: 28},
  {nome: "Aroazes", unidade_federativa_id: 28},
  {nome: "Aroeiras do Itaim", unidade_federativa_id: 28},
  {nome: "Arraial", unidade_federativa_id: 28},
  {nome: "Assunção do Piauí", unidade_federativa_id: 28},
  {nome: "Avelino Lopes", unidade_federativa_id: 28},
  {nome: "Baixa Grande do Ribeiro", unidade_federativa_id: 28},
  {nome: "Barra D'Alcântara", unidade_federativa_id: 28},
  {nome: "Barras", unidade_federativa_id: 28},
  {nome: "Barreiras do Piauí", unidade_federativa_id: 28},
  {nome: "Barro Duro", unidade_federativa_id: 28},
  {nome: "Batalha", unidade_federativa_id: 28},
  {nome: "Bela Vista do Piauí", unidade_federativa_id: 28},
  {nome: "Belém do Piauí", unidade_federativa_id: 28},
  {nome: "Beneditinos", unidade_federativa_id: 28},
  {nome: "Bertolínia", unidade_federativa_id: 28},
  {nome: "Betânia do Piauí", unidade_federativa_id: 28},
  {nome: "Boa Hora", unidade_federativa_id: 28},
  {nome: "Bocaina", unidade_federativa_id: 28},
  {nome: "Bom Jesus", unidade_federativa_id: 28},
  {nome: "Bom Princípio do Piauí", unidade_federativa_id: 28},
  {nome: "Bonfim do Piauí", unidade_federativa_id: 28},
  {nome: "Boqueirão do Piauí", unidade_federativa_id: 28},
  {nome: "Brasileira", unidade_federativa_id: 28},
  {nome: "Brejo do Piauí", unidade_federativa_id: 28},
  {nome: "Buriti dos Lopes", unidade_federativa_id: 28},
  {nome: "Buriti dos Montes", unidade_federativa_id: 28},
  {nome: "Cabeceiras do Piauí", unidade_federativa_id: 28},
  {nome: "Cajazeiras do Piauí", unidade_federativa_id: 28},
  {nome: "Cajueiro da Praia", unidade_federativa_id: 28},
  {nome: "Caldeirão Grande do Piauí", unidade_federativa_id: 28},
  {nome: "Campinas do Piauí", unidade_federativa_id: 28},
  {nome: "Campo Alegre do Fidalgo", unidade_federativa_id: 28},
  {nome: "Campo Grande do Piauí", unidade_federativa_id: 28},
  {nome: "Campo Largo do Piauí", unidade_federativa_id: 28},
  {nome: "Campo Maior", unidade_federativa_id: 28},
  {nome: "Canavieira", unidade_federativa_id: 28},
  {nome: "Canto do Buriti", unidade_federativa_id: 28},
  {nome: "Capitão Gervásio Oliveira", unidade_federativa_id: 28},
  {nome: "Capitão de Campos", unidade_federativa_id: 28},
  {nome: "Caracol", unidade_federativa_id: 28},
  {nome: "Caraúbas do Piauí", unidade_federativa_id: 28},
  {nome: "Caridade do Piauí", unidade_federativa_id: 28},
  {nome: "Castelo do Piauí", unidade_federativa_id: 28},
  {nome: "Caxingó", unidade_federativa_id: 28},
  {nome: "Cocal", unidade_federativa_id: 28},
  {nome: "Cocal de Telha", unidade_federativa_id: 28},
  {nome: "Cocal dos Alves", unidade_federativa_id: 28},
  {nome: "Coivaras", unidade_federativa_id: 28},
  {nome: "Colônia do Gurguéia", unidade_federativa_id: 28},
  {nome: "Colônia do Piauí", unidade_federativa_id: 28},
  {nome: "Conceição do Canindé", unidade_federativa_id: 28},
  {nome: "Coronel José Dias", unidade_federativa_id: 28},
  {nome: "Corrente", unidade_federativa_id: 28},
  {nome: "Cristalândia do Piauí", unidade_federativa_id: 28},
  {nome: "Cristino Castro", unidade_federativa_id: 28},
  {nome: "Curimatá", unidade_federativa_id: 28},
  {nome: "Currais", unidade_federativa_id: 28},
  {nome: "Curral Novo do Piauí", unidade_federativa_id: 28},
  {nome: "Curralinhos", unidade_federativa_id: 28},
  {nome: "Demerval Lobão", unidade_federativa_id: 28},
  {nome: "Dirceu Arcoverde", unidade_federativa_id: 28},
  {nome: "Dom Expedito Lopes", unidade_federativa_id: 28},
  {nome: "Dom Inocêncio", unidade_federativa_id: 28},
  {nome: "Domingos Mourão", unidade_federativa_id: 28},
  {nome: "Elesbão Veloso", unidade_federativa_id: 28},
  {nome: "Eliseu Martins", unidade_federativa_id: 28},
  {nome: "Esperantina", unidade_federativa_id: 28},
  {nome: "Fartura do Piauí", unidade_federativa_id: 28},
  {nome: "Flores do Piauí", unidade_federativa_id: 28},
  {nome: "Floresta do Piauí", unidade_federativa_id: 28},
  {nome: "Floriano", unidade_federativa_id: 28},
  {nome: "Francinópolis", unidade_federativa_id: 28},
  {nome: "Francisco Ayres", unidade_federativa_id: 28},
  {nome: "Francisco Macedo", unidade_federativa_id: 28},
  {nome: "Francisco Santos", unidade_federativa_id: 28},
  {nome: "Fronteiras", unidade_federativa_id: 28},
  {nome: "Geminiano", unidade_federativa_id: 28},
  {nome: "Gilbués", unidade_federativa_id: 28},
  {nome: "Guadalupe", unidade_federativa_id: 28},
  {nome: "Guaribas", unidade_federativa_id: 28},
  {nome: "Hugo Napoleão", unidade_federativa_id: 28},
  {nome: "Ilha Grande", unidade_federativa_id: 28},
  {nome: "Inhuma", unidade_federativa_id: 28},
  {nome: "Ipiranga do Piauí", unidade_federativa_id: 28},
  {nome: "Isaías Coelho", unidade_federativa_id: 28},
  {nome: "Itainópolis", unidade_federativa_id: 28},
  {nome: "Itaueira", unidade_federativa_id: 28},
  {nome: "Jacobina do Piauí", unidade_federativa_id: 28},
  {nome: "Jaicós", unidade_federativa_id: 28},
  {nome: "Jardim do Mulato", unidade_federativa_id: 28},
  {nome: "Jatobá do Piauí", unidade_federativa_id: 28},
  {nome: "Jerumenha", unidade_federativa_id: 28},
  {nome: "Joaquim Pires", unidade_federativa_id: 28},
  {nome: "Joca Marques", unidade_federativa_id: 28},
  {nome: "José de Freitas", unidade_federativa_id: 28},
  {nome: "João Costa", unidade_federativa_id: 28},
  {nome: "Juazeiro do Piauí", unidade_federativa_id: 28},
  {nome: "Jurema", unidade_federativa_id: 28},
  {nome: "Júlio Borges", unidade_federativa_id: 28},
  {nome: "Lagoa Alegre", unidade_federativa_id: 28},
  {nome: "Lagoa de São Francisco", unidade_federativa_id: 28},
  {nome: "Lagoa do Barro do Piauí", unidade_federativa_id: 28},
  {nome: "Lagoa do Piauí", unidade_federativa_id: 28},
  {nome: "Lagoa do Sítio", unidade_federativa_id: 28},
  {nome: "Lagoinha do Piauí", unidade_federativa_id: 28},
  {nome: "Landri Sales", unidade_federativa_id: 28},
  {nome: "Luzilândia", unidade_federativa_id: 28},
  {nome: "Luís Correia", unidade_federativa_id: 28},
  {nome: "Madeiro", unidade_federativa_id: 28},
  {nome: "Manoel Emídio", unidade_federativa_id: 28},
  {nome: "Marcolândia", unidade_federativa_id: 28},
  {nome: "Marcos Parente", unidade_federativa_id: 28},
  {nome: "Massapê do Piauí", unidade_federativa_id: 28},
  {nome: "Matias Olímpio", unidade_federativa_id: 28},
  {nome: "Miguel Alves", unidade_federativa_id: 28},
  {nome: "Miguel Leão", unidade_federativa_id: 28},
  {nome: "Milton Brandão", unidade_federativa_id: 28},
  {nome: "Monsenhor Gil", unidade_federativa_id: 28},
  {nome: "Monsenhor Hipólito", unidade_federativa_id: 28},
  {nome: "Monte Alegre do Piauí", unidade_federativa_id: 28},
  {nome: "Morro Cabeça no Tempo", unidade_federativa_id: 28},
  {nome: "Morro do Chapéu do Piauí", unidade_federativa_id: 28},
  {nome: "Murici dos Portelas", unidade_federativa_id: 28},
  {nome: "Nazaré do Piauí", unidade_federativa_id: 28},
  {nome: "Nossa Senhora de Nazaré", unidade_federativa_id: 28},
  {nome: "Nossa Senhora dos Remédios", unidade_federativa_id: 28},
  {nome: "Nova Santa Rita", unidade_federativa_id: 28},
  {nome: "Novo Oriente do Piauí", unidade_federativa_id: 28},
  {nome: "Novo Santo Antônio", unidade_federativa_id: 28},
  {nome: "Oeiras", unidade_federativa_id: 28},
  {nome: "Olho D'Água do Piauí", unidade_federativa_id: 28},
  {nome: "Padre Marcos", unidade_federativa_id: 28},
  {nome: "Paes Landim", unidade_federativa_id: 28},
  {nome: "Pajeú do Piauí", unidade_federativa_id: 28},
  {nome: "Palmeira do Piauí", unidade_federativa_id: 28},
  {nome: "Palmeirais", unidade_federativa_id: 28},
  {nome: "Paquetá", unidade_federativa_id: 28},
  {nome: "Parnaguá", unidade_federativa_id: 28},
  {nome: "Parnaíba", unidade_federativa_id: 28},
  {nome: "Passagem Franca do Piauí", unidade_federativa_id: 28},
  {nome: "Patos do Piauí", unidade_federativa_id: 28},
  {nome: "Pau D'Arco do Piauí", unidade_federativa_id: 28},
  {nome: "Paulistana", unidade_federativa_id: 28},
  {nome: "Pavussu", unidade_federativa_id: 28},
  {nome: "Pedro II", unidade_federativa_id: 28},
  {nome: "Pedro Laurentino", unidade_federativa_id: 28},
  {nome: "Picos", unidade_federativa_id: 28},
  {nome: "Pimenteiras", unidade_federativa_id: 28},
  {nome: "Pio IX", unidade_federativa_id: 28},
  {nome: "Piracuruca", unidade_federativa_id: 28},
  {nome: "Piripiri", unidade_federativa_id: 28},
  {nome: "Porto", unidade_federativa_id: 28},
  {nome: "Porto Alegre do Piauí", unidade_federativa_id: 28},
  {nome: "Prata do Piauí", unidade_federativa_id: 28},
  {nome: "Queimada Nova", unidade_federativa_id: 28},
  {nome: "Redenção do Gurguéia", unidade_federativa_id: 28},
  {nome: "Regeneração", unidade_federativa_id: 28},
  {nome: "Riacho Frio", unidade_federativa_id: 28},
  {nome: "Ribeira do Piauí", unidade_federativa_id: 28},
  {nome: "Ribeiro Gonçalves", unidade_federativa_id: 28},
  {nome: "Rio Grande do Piauí", unidade_federativa_id: 28},
  {nome: "Santa Cruz do Piauí", unidade_federativa_id: 28},
  {nome: "Santa Cruz dos Milagres", unidade_federativa_id: 28},
  {nome: "Santa Filomena", unidade_federativa_id: 28},
  {nome: "Santa Luz", unidade_federativa_id: 28},
  {nome: "Santa Rosa do Piauí", unidade_federativa_id: 28},
  {nome: "Santana do Piauí", unidade_federativa_id: 28},
  {nome: "Santo Antônio de Lisboa", unidade_federativa_id: 28},
  {nome: "Santo Antônio dos Milagres", unidade_federativa_id: 28},
  {nome: "Santo Inácio do Piauí", unidade_federativa_id: 28},
  {nome: "Sebastião Barros", unidade_federativa_id: 28},
  {nome: "Sebastião Leal", unidade_federativa_id: 28},
  {nome: "Sigefredo Pacheco", unidade_federativa_id: 28},
  {nome: "Simplício Mes", unidade_federativa_id: 28},
  {nome: "Simões", unidade_federativa_id: 28},
  {nome: "Socorro do Piauí", unidade_federativa_id: 28},
  {nome: "Sussuapara", unidade_federativa_id: 28},
  {nome: "São Braz do Piauí", unidade_federativa_id: 28},
  {nome: "São Francisco de Assis do Piauí", unidade_federativa_id: 28},
  {nome: "São Francisco do Piauí", unidade_federativa_id: 28},
  {nome: "São Félix do Piauí", unidade_federativa_id: 28},
  {nome: "São Gonçalo do Gurguéia", unidade_federativa_id: 28},
  {nome: "São Gonçalo do Piauí", unidade_federativa_id: 28},
  {nome: "São José do Divino", unidade_federativa_id: 28},
  {nome: "São José do Peixe", unidade_federativa_id: 28},
  {nome: "São José do Piauí", unidade_federativa_id: 28},
  {nome: "São João da Canabrava", unidade_federativa_id: 28},
  {nome: "São João da Fronteira", unidade_federativa_id: 28},
  {nome: "São João da Serra", unidade_federativa_id: 28},
  {nome: "São João da Varjota", unidade_federativa_id: 28},
  {nome: "São João do Arraial", unidade_federativa_id: 28},
  {nome: "São João do Piauí", unidade_federativa_id: 28},
  {nome: "São Julião", unidade_federativa_id: 28},
  {nome: "São Lourenço do Piauí", unidade_federativa_id: 28},
  {nome: "São Luis do Piauí", unidade_federativa_id: 28},
  {nome: "São Miguel da Baixa Grande", unidade_federativa_id: 28},
  {nome: "São Miguel do Fidalgo", unidade_federativa_id: 28},
  {nome: "São Miguel do Tapuio", unidade_federativa_id: 28},
  {nome: "São Pedro do Piauí", unidade_federativa_id: 28},
  {nome: "São Raimundo Nonato", unidade_federativa_id: 28},
  {nome: "Tamboril do Piauí", unidade_federativa_id: 28},
  {nome: "Tanque do Piauí", unidade_federativa_id: 28},
  {nome: "Teresina", unidade_federativa_id: 28},
  {nome: "União", unidade_federativa_id: 28},
  {nome: "Uruçuí", unidade_federativa_id: 28},
  {nome: "Valença do Piauí", unidade_federativa_id: 28},
  {nome: "Vera Mes", unidade_federativa_id: 28},
  {nome: "Vila Nova do Piauí", unidade_federativa_id: 28},
  {nome: "Várzea Branca", unidade_federativa_id: 28},
  {nome: "Várzea Grande", unidade_federativa_id: 28},
  {nome: "Wall Ferraz", unidade_federativa_id: 28}
])
Nivel.create!([
  {descricao: "Basico"},
  {descricao: "Intermediario"},
  {descricao: "Avancado"}
])
UnidadeFederativa.create!([
  {sigla: "AC", nome: "Acre"},
  {sigla: "AL", nome: "Alagoas"},
  {sigla: "AM", nome: "Amazonas"},
  {sigla: "AP", nome: "Amapá"},
  {sigla: "BA", nome: "Bahia"},
  {sigla: "CE", nome: "Ceará"},
  {sigla: "DF", nome: "Distrito Federal"},
  {sigla: "ES", nome: "Espírito Santo"},
  {sigla: "GO", nome: "Goiás"},
  {sigla: "MA", nome: "Maranhão"},
  {sigla: "MG", nome: "Minas Gerais"},
  {sigla: "MS", nome: "Mato Grosso do Sul"},
  {sigla: "MT", nome: "Mato Grosso"},
  {sigla: "PA", nome: "Pará"},
  {sigla: "PB", nome: "Paraíba"},
  {sigla: "PE", nome: "Pernambuco"},
  {sigla: "PI", nome: "Piauí"},
  {sigla: "PR", nome: "Paraná"},
  {sigla: "RJ", nome: "Rio de Janeiro"},
  {sigla: "RN", nome: "Rio Grande do Norte"},
  {sigla: "RO", nome: "Rondônia"},
  {sigla: "RR", nome: "Roraima"},
  {sigla: "RS", nome: "Rio Grande do Sul"},
  {sigla: "SC", nome: "Santa Catarina"},
  {sigla: "SE", nome: "Sergipe"},
  {sigla: "SP", nome: "São Paulo"},
  {sigla: "TO", nome: "Tocantins"},
  {sigla: "PI", nome: "Piauí"}
])
Usuario.create!([
  {login: "candidato1", password_digest: "$2a$10$7a7oMqHXYxRiLGd1uG6aXeBG9DhgQllbKTEP3wLq3.136gJxUHgBO", status: true, papel: "candidato", pessoa_id: 1},
  {login: "contratante1", password_digest: "$2a$10$7a7oMqHXYxRiLGd1uG6aXeBG9DhgQllbKTEP3wLq3.136gJxUHgBO", status: true, papel: "contratante", pessoa_id: 2}
])
Vaga.create!([
  {contratante_id: 2, faixa_salarial_id: 1, cidade_id: 336, quantidade: "1", cargo: "Analista de TI", descricao: "Descricao Analista de TI", data_cadastro: "2015-01-01", data_inicio_inscricao: "2015-01-01", data_termino_inscricao: nil},
  {contratante_id: 2, faixa_salarial_id: 1, cidade_id: 336, quantidade: "2", cargo: "Analista de TI 2", descricao: "Descricao Analista de TI 2", data_cadastro: "2015-01-01", data_inicio_inscricao: "2015-01-01", data_termino_inscricao: nil}
])
Candidato.create!([
  {nome: "Pessoa 2", email: "pessoa2", telefone: "887987312", logradouro: "Rua 2", complemento: "ap2", numero: "2", bairro: "bairro2", municipio_id: 336, cep: "342423423", type: "Candidato", cpf: "4233342322", dataNascimento: "1965-01-01", naturalidade_id: 336, nacionalidade: "Salvador", foto: nil, inscricaoEstadual: nil, cnpj: nil, logo: nil, autorizado: nil}
])
Contratante.create!([
  {nome: "Contratante 3", email: "pessoa3", telefone: "887987312", logradouro: "Rua 2", complemento: "ap2", numero: "2", bairro: "bairro2", municipio_id: 336, cep: "342423423", type: "Contratante", cpf: "4233342322", dataNascimento: "1965-01-01", naturalidade_id: nil, nacionalidade: nil, foto: nil, inscricaoEstadual: nil, cnpj: nil, logo: nil, autorizado: nil},
  {nome: "Contratante 4", email: "dsad@dfsd", telefone: "2331", logradouro: "34", complemento: "342", numero: "122", bairro: "afça", municipio_id: 8, cep: "34234", type: "Contratante", cpf: nil, dataNascimento: nil, naturalidade_id: nil, nacionalidade: nil, foto: nil, inscricaoEstadual: "3423", cnpj: "3424", logo: "", autorizado: true}
])
